### ISSUE TITLE
Nothing to see here

### ISSUE THREAD

**Issue by Vogtinator** [Vogtinator/usbredir2phys#1]

**Comment by Red967** [comment]
Is it a working project or not?

**Comment by Vogtinator** [comment]
Yes, this was working fine at the time of the last commit. Currently I lack USB device controller hardware though, so I wouldn't be able to debug and fix issues though.

**Comment by Red967** [comment]
What if i'm always getting segmentation error?

**Comment by Vogtinator** [comment]
Please open an issue with a full backtrace and I'll have a look.
